#!/bin/bash

temp_file=$(mktemp)
if [ "$#" -eq 0 ]; then
  echo > "$temp_file" 2>&1
elif [[ "$1" == "rb" || "$1" == "tsx" || "$1" == "java"  || "$1" == "md" || "$1" == "json" ]]; then
  mv "$temp_file" "${temp_file}.$1"
  temp_file="${temp_file}.$1"
else
  "$@" > "$temp_file" 2>&1
fi

if [ $? -ne 0 ]; then
  echo "Command failed"
else
  echo "Command worked"
fi

nvim "$temp_file"

rm "$temp_file"

