[tools]
go = "1.23"
ruby = "latest"
zig = "latest"
zls = "latest"
bun = "latest"
rust = "latest"
typst = "latest"
tinymist = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
codex = "latest"
herdr = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"npm:pyright" = "latest"
"github:can1357/oh-my-pi" = "latest"
