[tools]
go = "1.23"
ruby = "latest"
zig = "latest"
zls = "latest"
bun = "latest"
typst = "latest"
tinymist = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
